name: otomasi deploy server
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/be16app:latest 
    - 
      name: multiple command
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          docker stop mysql96
docker rm mysql96
docker rmi be16prj:latest
docker run --name mysql96 -d -p 8080:8080 --network=my-network -e USER=${{ secrets.DBUSER }} -e PASSWORD={{ secrets.DBPASSWORD }} -e HOST=${{ secrets.DBHOST }} -e PORT=${{ secrets.DBPORT }} -e NAME=${{ secrets.DBNAME }} -e JWT_SECRET=${{ secrets.JWT }} be16prj:latest


